
#ifndef _ORE_NAMESPACES_H_
#define _ORE_NAMESPACES_H_

#define ORE_NAMESPACE_NAME ore
#define ORE_INTERNAL_NAMESPACE_NAME Internal

#define ORE_NAMESPACE_START namespace ORE_NAMESPACE_NAME {
#define ORE_NAMESPACE_END }

#define ORE_INTERNAL_NAMESPACE_START namespace ORE_INTERNAL_NAMESPACE_NAME {
#define ORE_INTERNAL_NAMESPACE_END  }

#endif